version: "3.9"
services:
  yb-master-0:
    image: yugabytedb/yugabyte:2.18.0.1-b4
    platform: linux/amd64
    cap_add:
      - NET_ADMIN
    container_name: yb-master-0
    hostname: yb-master-0.zone.region.cloud
    command:
      - bash
      - -c
      - |
        rm -rf /tmp/.yb* ;
        /home/yugabyte/bin/yb-master \
          --ysql_beta_feature_tablespace_alteration=true \
          --ysql_enable_packed_row=true \
          --ysql_beta_features=true \
          --yb_enable_read_committed_isolation=true \
          --default_memory_limit_to_ram_ratio=0.20 \
          --fs_data_dirs=/home/yugabyte/data \
          --placement_cloud=cloud \
          --placement_region=region \
          --placement_zone=zone \
          --rpc_bind_addresses=yb-master-0.zone.region.cloud:7100 \
          --master_addresses=yb-master-0:7100,yb-master-1:7100,yb-master-2:7100 \
          --replication_factor=3 \
          --rpc_connection_timeout_ms=15000

    restart: unless-stopped
    ports:
      - "7000:7000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://yb-master-0"]
      start_period: 5s
      interval: 10s
      timeout: 5s
      retries: 3
  yb-master-1:
    image: yugabytedb/yugabyte:2.18.0.1-b4
    platform: linux/amd64
    cap_add:
      - NET_ADMIN
    container_name: yb-master-1
    hostname: yb-master-1.zone.region.cloud
    command:
      - bash
      - -c
      - |
        rm -rf /tmp/.yb* ;
        /home/yugabyte/bin/yb-master \
          --ysql_beta_feature_tablespace_alteration=true \
          --ysql_enable_packed_row=true \
          --ysql_beta_features=true \
          --yb_enable_read_committed_isolation=true \
          --default_memory_limit_to_ram_ratio=0.20 \
          --fs_data_dirs=/home/yugabyte/data \
          --placement_cloud=cloud \
          --placement_region=region \
          --placement_zone=zone \
          --rpc_bind_addresses=yb-master-1.zone.region.cloud:7100 \
          --master_addresses=yb-master-0:7100,yb-master-1:7100,yb-master-2:7100 \
          --replication_factor=3 \
          --rpc_connection_timeout_ms=15000

    restart: unless-stopped
    ports:
      - "7001:7000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://yb-master-1"]
      start_period: 5s
      interval: 10s
      timeout: 5s
      retries: 3

  yb-master-2:
    image: yugabytedb/yugabyte:2.18.0.1-b4
    platform: linux/amd64
    cap_add:
      - NET_ADMIN
    container_name: yb-master-2
    hostname: yb-master-2.zone.region.cloud
    command:
      - bash
      - -c
      - |
        rm -rf /tmp/.yb* ;
        /home/yugabyte/bin/yb-master \
          --ysql_beta_feature_tablespace_alteration=true \
          --ysql_enable_packed_row=true \
          --ysql_beta_features=true \
          --yb_enable_read_committed_isolation=true \
          --default_memory_limit_to_ram_ratio=0.20 \
          --fs_data_dirs=/home/yugabyte/data \
          --placement_cloud=cloud \
          --placement_region=region \
          --placement_zone=zone \
          --rpc_bind_addresses=yb-master-2.zone.region.cloud:7100 \
          --master_addresses=yb-master-0:7100,yb-master-1:7100,yb-master-2:7100 \
          --replication_factor=3 \
          --rpc_connection_timeout_ms=15000

    restart: unless-stopped
    ports:
      - "7002:7000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://yb-master-2"]
      start_period: 5s
      interval: 10s
      timeout: 5s
      retries: 3
  yb-tserver-0:
    image: yugabytedb/yugabyte:2.18.0.1-b4
    platform: linux/amd64
    cap_add:
      - NET_ADMIN
    container_name: yb-tserver-0
    hostname: yb-tserver-0.zone.region.cloud
    command:
      - bash
      - -c
      - |
        rm -rf /tmp/.yb* ;
        /home/yugabyte/bin/yb-tserver \
          --ysql_beta_feature_tablespace_alteration=true \
          --ysql_enable_packed_row=true \
          --ysql_beta_features=true \
          --yb_enable_read_committed_isolation=true \
          --default_memory_limit_to_ram_ratio=0.20 \
          --placement_cloud=cloud \
          --placement_region=region \
          --placement_zone=zone \
          --enable_ysql=true \
          --fs_data_dirs=/home/yugabyte/data \
          --rpc_bind_addresses=yb-tserver-0.zone.region.cloud:9100 \
          --tserver_master_addrs=yb-master-0:7100,yb-master-1:7100,yb-master-2:7100 \
          --ysql_num_shards_per_tserver=2 \
          --rpc_connection_timeout_ms=15000

    restart: unless-stopped
    ports:
      - "9000:9000"
      - "5433:5433"
    healthcheck:
      test:
        ["CMD", "/home/yugabyte/postgres/bin/pg_isready", "-h", "yb-tserver-0"]
      start_period: 5s
      interval: 10s
      timeout: 5s
      retries: 10

  yb-tserver-1:
    image: yugabytedb/yugabyte:2.18.0.1-b4
    platform: linux/amd64
    cap_add:
      - NET_ADMIN
    container_name: yb-tserver-1
    hostname: yb-tserver-1.zone.region.cloud
    command:
      - bash
      - -c
      - |
        rm -rf /tmp/.yb* ;
        /home/yugabyte/bin/yb-tserver \
          --ysql_beta_feature_tablespace_alteration=true \
          --ysql_enable_packed_row=true \
          --ysql_beta_features=true \
          --yb_enable_read_committed_isolation=true \
          --default_memory_limit_to_ram_ratio=0.20 \
          --placement_cloud=cloud \
          --placement_region=region \
          --placement_zone=zone \
          --enable_ysql=true \
          --fs_data_dirs=/home/yugabyte/data \
          --rpc_bind_addresses=yb-tserver-1.zone.region.cloud:9100 \
          --tserver_master_addrs=yb-master-0:7100,yb-master-1:7100,yb-master-2:7100 \
          --ysql_num_shards_per_tserver=2 \
          --rpc_connection_timeout_ms=15000

    restart: unless-stopped
    ports:
      - "9001:9000"
      - "5434:5433"
    healthcheck:
      test:
        ["CMD", "/home/yugabyte/postgres/bin/pg_isready", "-h", "yb-tserver-1"]
      start_period: 5s
      interval: 10s
      timeout: 5s
      retries: 10

  yb-tserver-2:
    image: yugabytedb/yugabyte:2.18.0.1-b4
    platform: linux/amd64
    cap_add:
      - NET_ADMIN
    container_name: yb-tserver-2
    hostname: yb-tserver-2.zone.region.cloud
    command:
      - bash
      - -c
      - |
        rm -rf /tmp/.yb* ;
        /home/yugabyte/bin/yb-tserver \
          --ysql_beta_feature_tablespace_alteration=true \
          --ysql_enable_packed_row=true \
          --ysql_beta_features=true \
          --yb_enable_read_committed_isolation=true \
          --default_memory_limit_to_ram_ratio=0.20 \
          --placement_cloud=cloud \
          --placement_region=region \
          --placement_zone=zone \
          --enable_ysql=true \
          --fs_data_dirs=/home/yugabyte/data \
          --rpc_bind_addresses=yb-tserver-2.zone.region.cloud:9100 \
          --tserver_master_addrs=yb-master-0:7100,yb-master-1:7100,yb-master-2:7100 \
          --ysql_num_shards_per_tserver=2 \
          --rpc_connection_timeout_ms=15000

    restart: unless-stopped
    ports:
      - "9002:9000"
      - "5435:5433"
    healthcheck:
      test:
        ["CMD", "/home/yugabyte/postgres/bin/pg_isready", "-h", "yb-tserver-2"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      dockerfile: demo.Dockerfile
    container_name: app
    hostname: app.zone.region.cloud
    environment:
        SPRING_DATASOURCE_HIKARI_DATA_SOURCE_PROPERTIES_SERVERNAME: yb-tserver-0
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      yb-tserver-0:
        condition: service_healthy
